spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

accounts:
  message: "Welcome to Eazybank related QA APIs"
  contactDetails:
    name: "Smitha Ray QA Lead"
    email: "smitha@eazybank.com"
  onCallSupport:
    -(666)666-1234
    -(666)523-1345